services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: posgrados
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: bd_record
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posgrados -d bd_record"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
